/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'productId' : bigint,
  'quantity' : bigint,
  'priceAtOrder' : bigint,
}
export interface CancelNotification {
  'id' : bigint,
  'orderId' : bigint,
  'buyerPrincipal' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'buyerId' : Principal,
  'items' : Array<CartItem>,
  'paymentMethod' : string,
  'paymentScreenshotId' : string,
}
export interface PaymentQRs {
  'esewaQrImageId' : string,
  'bankQrImageId' : string,
}
export interface Product {
  'id' : bigint,
  'stockQty' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'discountPercent' : bigint,
  'isActive' : boolean,
  'category' : string,
  'imageId' : string,
  'price' : bigint,
}
export interface ProductInput {
  'stockQty' : bigint,
  'name' : string,
  'description' : string,
  'discountPercent' : bigint,
  'category' : string,
  'imageId' : string,
  'price' : bigint,
}
export interface ProductUpdateInput {
  'id' : bigint,
  'stockQty' : bigint,
  'name' : string,
  'description' : string,
  'discountPercent' : bigint,
  'category' : string,
  'imageId' : string,
  'price' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createProduct' : ActorMethod<[ProductInput], bigint>,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAdminCancelNotifications' : ActorMethod<[], Array<CancelNotification>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProductsAdmin' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getInsights' : ActorMethod<
    [],
    {
      'cancelledOrders' : bigint,
      'totalOrders' : bigint,
      'pendingOrders' : bigint,
      'processingOrders' : bigint,
      'completedOrders' : bigint,
    }
  >,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getPaymentQRs' : ActorMethod<[], PaymentQRs>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginAsAdmin' : ActorMethod<[string], boolean>,
  'markCancelNotificationRead' : ActorMethod<[bigint], undefined>,
  'placeOrder' : ActorMethod<[string, string], bigint>,
  'removeCartItem' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPaymentQRs' : ActorMethod<[string, string], undefined>,
  'toggleProductActive' : ActorMethod<[bigint, boolean], undefined>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<[ProductUpdateInput], undefined>,
  'updateProductStock' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
