/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'category' : IDL.Text,
  'imageId' : IDL.Text,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'imageId' : IDL.Text,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'priceAtOrder' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'buyerId' : IDL.Principal,
  'items' : IDL.Vec(CartItem),
  'paymentMethod' : IDL.Text,
  'paymentScreenshotId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductUpdateInput = IDL.Record({
  'id' : IDL.Nat,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'category' : IDL.Text,
  'imageId' : IDL.Text,
  'price' : IDL.Nat,
});
export const PaymentQRs = IDL.Record({
  'esewaQrImageId' : IDL.Text,
  'bankQrImageId' : IDL.Text,
});
export const CancelNotification = IDL.Record({
  'id' : IDL.Nat,
  'orderId' : IDL.Nat,
  'buyerPrincipal' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createProduct' : IDL.Func(
      [ProductInput],
      [IDL.Nat],
      [],
    ),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAdminCancelNotifications' : IDL.Func([], [IDL.Vec(CancelNotification)], ['query']),
  'getAllOrders' : IDL.Func(
      [],
      [IDL.Vec(Order)],
      [],
    ),
  'getAllProductsAdmin' : IDL.Func(
      [],
      [IDL.Vec(Product)],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], []),
  'getInsights' : IDL.Func(
      [],
      [
        IDL.Record({
          'cancelledOrders' : IDL.Nat,
          'totalOrders' : IDL.Nat,
          'pendingOrders' : IDL.Nat,
          'processingOrders' : IDL.Nat,
          'completedOrders' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getPaymentQRs' : IDL.Func([], [PaymentQRs], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginAsAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'markCancelNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'removeCartItem' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPaymentQRs' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'toggleProductActive' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [ProductUpdateInput],
      [],
      [],
    ),
  'updateProductStock' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'category' : IDL.Text,
    'imageId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'imageId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'priceAtOrder' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'buyerId' : IDL.Principal,
    'items' : IDL.Vec(CartItem),
    'paymentMethod' : IDL.Text,
    'paymentScreenshotId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductUpdateInput = IDL.Record({
    'id' : IDL.Nat,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'category' : IDL.Text,
    'imageId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const PaymentQRs = IDL.Record({
    'esewaQrImageId' : IDL.Text,
    'bankQrImageId' : IDL.Text,
  });
  const CancelNotification = IDL.Record({
    'id' : IDL.Nat,
    'orderId' : IDL.Nat,
    'buyerPrincipal' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createProduct' : IDL.Func(
        [ProductInput],
        [IDL.Nat],
        [],
      ),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAdminCancelNotifications' : IDL.Func([], [IDL.Vec(CancelNotification)], ['query']),
    'getAllOrders' : IDL.Func(
        [],
        [IDL.Vec(Order)],
        [],
      ),
    'getAllProductsAdmin' : IDL.Func(
        [],
        [IDL.Vec(Product)],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], []),
    'getInsights' : IDL.Func(
        [],
        [
          IDL.Record({
            'cancelledOrders' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'pendingOrders' : IDL.Nat,
            'processingOrders' : IDL.Nat,
            'completedOrders' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getPaymentQRs' : IDL.Func([], [PaymentQRs], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginAsAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'markCancelNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'removeCartItem' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPaymentQRs' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'toggleProductActive' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductUpdateInput],
        [],
        [],
      ),
    'updateProductStock' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
